version: '3'

services:

  app:
    build:
      context: ./
      dockerfile: Dockerfile.app
    env_file: .env
    ports:
      - ${APP_PORT}:80

  dev:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src:delegated
    env_file: .env
    ports:
      - ${DEV_PORT}:5000